// app-react/src/layouts/LandingPage.tsx
import logo from '../../../assets/logo.svg';
//({ title }: { title: string })
function LandingPage({msg}: { msg: String }) {
	return (
		<div className="layout-content">
		<img alt="Schwaasz logo" src={logo} />

		<div className="hello">
			<h1>{msg}</h1>
			<p>
				click the DOG button to navigate to the sheet data template
			</p>
		</div>
		</div>
	)
}

export default LandingPage;

// src/components/LandingPage.vue
<template>
  <img alt="Schwaasz logo" src="./assets/logo.png">
  <div class="hello">
    <h1>{{ msg }}</h1>
    <p>
      click the DOG button to navigate to the sheet data template
    </p>
  </div>
</template>

<script lang="ts">
export default {
  name: 'LandingPage',
  props: {
    msg: String
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  display: inline-block;
  margin: 0 10px;
}

a {
  color: #42b983;
}

img {
  width: 200px;
}
</style>
